"""OpenSCAD template plugin for ModuMesh MakerLab.

Generates parametric boxes, organizers, and trays using a pinned
headless OpenSCAD runtime. Parameters are written to a safe definitions
file — never accepts raw user script input.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from modumesh_plugin_sdk import PluginContext

# Templates bundled with the plugin (read-only, never user-supplied)
TEMPLATES_DIR = Path(__file__).resolve().parent.parent.parent / "templates"

ALLOWED_TEMPLATES: dict[str, str] = {
    "storage-box": "storage-box.scad",
    "grid-organizer": "grid-organizer.scad",
    "parts-tray": "parts-tray.scad",
}


def _safe_param_value(val: Any) -> str:
    """Convert a JSON-schema-validated value to an OpenSCAD assignment string."""
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, int):
        return str(val)
    if isinstance(val, float):
        # Format without scientific notation, trim trailing zeros
        return f"{val:.6f}".rstrip("0").rstrip(".") or "0"
    if isinstance(val, str):
        # OpenSCAD string — escape quotes and backslashes
        safe = val.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{safe}"'
    raise ValueError(f"Unsupported parameter type: {type(val).__name__}")


def _write_params(params: dict[str, Any], path: Path) -> None:
    """Write validated parameters as OpenSCAD variable assignments.

    Only numeric, boolean, and string values are emitted. All values
    have been validated against the JSON Schema already.
    """
    lines: list[str] = [
        "// Auto-generated parameter definitions — DO NOT EDIT",
        f"// Generated by {__name__}",
        "",
    ]
    for key, value in sorted(params.items()):
        if key == "template":
            continue
        try:
            sv = _safe_param_value(value)
            lines.append(f"{key} = {sv};")
        except ValueError:
            continue  # silently skip unsupported

    lines.append("")  # trailing newline
    path.write_text("\n".join(lines), encoding="utf-8")


def _openscad_version() -> str:
    """Get OpenSCAD version string from CLI."""
    try:
        result = subprocess.run(
            ["openscad", "--version"],
            capture_output=True, text=True, timeout=10,
        )
        return result.stdout.strip() or result.stderr.strip() or "unknown"
    except Exception:
        return "unknown"


def _export_glb_from_stl(stl_path: str, glb_path: str) -> None:
    """Convert STL to GLB using trimesh."""
    try:
        import trimesh
        mesh = trimesh.load(stl_path)
        mesh.export(glb_path, file_type="glb")
    except ImportError:
        shutil.copyfile(stl_path, glb_path)


def run(ctx: "PluginContext") -> None:
    """Generate an OpenSCAD template from input parameters."""
    ctx.set_progress(5, "validating input")

    inp = ctx.input
    template_name = str(inp.get("template", "storage-box"))

    # Validate template name (path injection protection)
    if template_name not in ALLOWED_TEMPLATES:
        raise ValueError(
            f"Unknown template '{template_name}'. "
            f"Allowed: {', '.join(sorted(ALLOWED_TEMPLATES))}"
        )

    template_file = TEMPLATES_DIR / ALLOWED_TEMPLATES[template_name]
    if not template_file.is_file():
        raise FileNotFoundError(f"Template file not found: {template_file}")

    # Validate numeric parameters
    width = float(inp.get("width", 120))
    depth = float(inp.get("depth", 80))
    height = float(inp.get("height", 50))
    wall_thickness = float(inp.get("wall_thickness", 2))
    bottom_thickness = float(inp.get("bottom_thickness", 2))
    corner_radius = float(inp.get("corner_radius", 3))
    include_lid = bool(inp.get("include_lid", False))
    lid_clearance = float(inp.get("lid_clearance", 0.3))
    grid_cells_x = int(inp.get("grid_cells_x", 3))
    grid_cells_y = int(inp.get("grid_cells_y", 2))

    # Clamp values
    width = max(20, min(400, width))
    depth = max(20, min(400, depth))
    height = max(10, min(200, height))
    wall_thickness = max(0.8, min(10, wall_thickness))
    bottom_thickness = max(0.8, min(10, bottom_thickness))
    corner_radius = max(0, min(20, corner_radius))
    lid_clearance = max(0.1, min(2, lid_clearance))
    grid_cells_x = max(1, min(12, grid_cells_x))
    grid_cells_y = max(1, min(12, grid_cells_y))

    # Validate geometry constraints
    if wall_thickness * 2 >= width or wall_thickness * 2 >= depth:
        raise ValueError(
            f"wall_thickness {wall_thickness}mm exceeds half of "
            f"width {width}mm or depth {depth}mm"
        )

    ctx.set_progress(15, "writing parameter definitions")

    # Build params dict for OpenSCAD
    params = {
        "box_width": width,
        "box_depth": depth,
        "box_height": height,
        "wall_thickness": wall_thickness,
        "bottom_thickness": bottom_thickness,
        "corner_radius": corner_radius,
        "include_lid": include_lid,
        "lid_clearance": lid_clearance,
        "grid_cells_x": grid_cells_x,
        "grid_cells_y": grid_cells_y,
    }

    work_dir = Path(ctx.work_dir)
    params_path = work_dir / "_params.scad"
    _write_params(params, params_path)

    # Record OpenSCAD version
    osc_version = _openscad_version()

    # Copy template to work dir so include <_params.scad> resolves
    local_template = work_dir / template_file.name
    shutil.copyfile(str(template_file), str(local_template))

    ctx.set_progress(30, f"running OpenSCAD ({template_name})")
    ctx.log(f"template={template_name} openscad={osc_version}")

    stl_path = work_dir / "model.stl"
    glb_path = work_dir / "model.glb"

    start_time = time.time()

    # Run OpenSCAD
    try:
        result = subprocess.run(
            [
                "openscad",
                "-o", str(stl_path),
                "--export-format", "binstl",
                str(local_template.name),
            ],
            cwd=str(work_dir),
            capture_output=True,
            text=True,
            timeout=110,
            env={**os.environ, "HOME": str(work_dir)},
        )
    except subprocess.TimeoutExpired:
        raise TimeoutError(
            f"OpenSCAD exceeded 110s timeout for template '{template_name}'"
        )

    duration_s = time.time() - start_time

    if result.returncode != 0:
        stderr_safe = result.stderr[-2000:] if result.stderr else "no stderr"
        raise RuntimeError(
            f"OpenSCAD failed (exit={result.returncode}): {stderr_safe}"
        )

    if not stl_path.is_file():
        raise FileNotFoundError(f"OpenSCAD did not produce {stl_path}")

    ctx.set_progress(60, "validating STL output")
    stl_size = stl_path.stat().st_size
    if stl_size < 100:
        raise RuntimeError(
            f"STL output suspiciously small ({stl_size} bytes)"
        )
    if stl_size > 10 * 1024 * 1024:
        raise RuntimeError(
            f"STL output exceeds 10 MB ({stl_size} bytes)"
        )

    ctx.register_output("model.stl")

    ctx.set_progress(75, "exporting GLB")
    _export_glb_from_stl(str(stl_path), str(glb_path))
    if glb_path.is_file():
        ctx.register_output("model.glb")

    # Write metadata
    ctx.set_progress(90, "writing metadata")
    stderr_log = result.stderr[-1000:] if result.stderr else ""
    ctx.write_json("meta.json", {
        "plugin_id": ctx.plugin_id,
        "plugin_version": ctx.plugin_version,
        "job_id": ctx.job_id,
        "template": template_name,
        "input": dict(inp),
        "outputs": {
            "model.stl": {
                "size_bytes": stl_size,
            },
            "model.glb": {
                "size_bytes": glb_path.stat().st_size if glb_path.is_file() else 0,
            },
        },
        "stats": {
            "generation_duration_s": round(duration_s, 2),
            "openscad_version": osc_version,
            "command_args": [
                "openscad",
                "-o", "model.stl",
                "--export-format", "binstl",
                str(local_template.name),
            ],
        },
        "warnings": (
            [line for line in stderr_log.split("\n") if line.strip()]
            if stderr_log
            else []
        ),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    })

    ctx.set_progress(100, "openscad template complete")
